name: Spring Boot Web Api

on: [push]

jobs:
  build:
    name: build Spring boot App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Git Clone
      uses: actions/checkout@v4

    - name: Install Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build Spring boot API
      run: |
        mvn clean install 